### ISSUE TITLE
Fix: Check Before Deleting File in Workflow

### ISSUE THREAD

**Issue by SethiShreya** [scribe-org/Scribe-Data#336]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Currently, the workflow deletes the file first and then extracts the data. This approach causes an issue where if an error occurs during data extraction, the previous file is already deleted and no new data is added, resulting in data loss.

**Steps to Reproduce:**

- Run the following command:
```scribe-data get --lang german -dt nouns```

- Carefully observe the workflow:
a. The file is deleted first.
b. Then the data extraction process begins.
c. If any error occurs during the data extraction, no new data is added, and the previous file is already deleted.

**Expected Behavior**: The system should first verify whether the data extraction process is successful before deleting the file. If the data extraction is error-free, then the file should be deleted.

**Proposed Fix:**

- Add a checking mechanism before deleting the file.
- Only proceed with file deletion if the data extraction process completes successfully without errors.

Impact: This will prevent unnecessary data loss in case of errors during the extraction phase.

**Comment by andrewtavis** [comment]
Thanks for the issue, @SethiShreya!

**Comment by andrewtavis** [comment]
@SethiShreya: Do you think that including totals lexemes regardless of data type in the total output makes sense? maybe as the first row of the table? Let me know and I can make an issue for it :)

**Comment by Otom-obhazi** [comment]
can i help??

**Comment by andrewtavis** [comment]
Hey @harikrishnatp 👋 There definitely are some cases where a file is being deleted without proper input. The SQLite conversion is one case where the old file is just replaced, so you could definitely work on this a bit. Let me know if you'd have interest and I can assign/provide more info if needed :)

**Comment by harikrishnatp** [comment]
I'm very new to the codebase, but I’ve had some experience with Scribe Data before, which is why I’m interested in contributing to this project. Could you point me to the relevant parts of the codebase that would help me better understand the issue and the SQLite conversion logic? Any specific areas or starting points I should focus on would be really helpful!

**Comment by harikrishnatp** [comment]
Thank you so much !

**Comment by andrewtavis** [comment]
Ok so the new version just got released, @harikrishnatp :) There are a few things to consider here in terms of checking before deleting a file:

- The `get` functionality (scribe-data get [arguments])
- The `convert` functionality (scribe-data convert [arguments])

I think that so far the `get` functionality is working well here as that's what @SethiShreya was focussed on 🎉 Would be good to test this, but then convert can be what we focus on at first. You can see the code for this command in [Scribe-Data/src/scribe_data/cli/convert.py](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/cli/convert.py). There are lots of `overwrite` arguments in the various functions, but then specifically for the `sqlite` conversion it's not respecting when we already have a database that might be overwritten.

You can see this with:
- `scribe-data get -lang German -dt prepositions  # relatively small dataset to test with`
- `scribe-data convert -lang German -dt prepositions -if scribe_data_json_export/German/prepositions.json -ot sqlite`
- Then run it again and we won't be asked if the database should be deleted
    - Beyond this, if the database has other tables in it, these are also deleted

Do you want to do some exploring and we can go from there? I'd suggest maybe bringing down German nouns and prepositions as JSON files, and then from there try converting them into csv and tsv as well as sqlite. Once the conversion is done, see what happens when you run it again with a file that will be overwritten :)

Beyond this, there is something that we could also fix for `get` that came up in testing for the above:

```bash
» scribe-data get -lang German -dt prepositions
Updating data for language(s): German; data type(s): Prepositions
Data updated:   0%|                                                                                                                      | 0/1 [00:00<?, ?process/s]
Existing file(s) found for German prepositions in the scribe_data_json_export directory:

1. prepositions.json

Choose an option:
1. Overwrite existing data (press 'o')
2. Skip process (press anything else)
Enter your choice: # I pressed enter
Skipping update for German prepositions.
Data updated:   0%|                                                                                                                      | 0/1 [00:02<?, ?process/s]
Updated data was saved in: MY_BASE_PATH/scribe-org/Scribe-Data/scribe_data_json_export.
```

See that we still get `Updated data was saved in...` even though we've skipped it? This might be a great first PR, and then we can move to the convert work?

Let me know what you think!

**Comment by harikrishnatp** [comment]
Thank you for the detailed explanations and guidance! 

Here's the plan I'm considering :

1. I'll start with the `convert` functionality to address the issue with `sqlite` conversion overwriting existing files or databases.
2. Move to the `get` functionality to fix the misleading log messages.

Do you think this approach makes sense ? also, is there a specific testing framework or methodology you'd recommend for verifying these fixes?

**Comment by andrewtavis** [comment]
Testing would be amazing to include in here! Your plan sounds good to me, and please add tests into the [tests](https://github.com/scribe-org/Scribe-Data/tree/main/tests) directory so that we can run them with pytest 😊

**Comment by harikrishnatp** [comment]
Thank you for the feedback! 

I'll start with option 2 instead of 1, as you suggested. Initially, I thought focusing on "convert" first would be better, but I now see that working on `get` first is a good way to get more familiar with the codebase.

I'll also include tests in the tests directory as part of this work and ensure they can be run with pytest.

I'll keep you updated on my progress!

**Comment by andrewtavis** [comment]
Looking forward to working with you, @harikrishnatp! :)

**Comment by harikrishnatp** [comment]
I'm sorry for being this late, I was caught up with some academic work

**Comment by andrewtavis** [comment]
Your academic work is more important than working on this, @harikrishnatp :) No worries at all! You should be able to follow the [testing process in the contributing guide](https://github.com/scribe-org/Scribe-Data/blob/main/CONTRIBUTING.md#testing), which is basically running `pytest` in the project root after you have the development environment set up. Let me know if that's not working or if you have a different question!

**Comment by harikrishnatp** [comment]
Thank you! I was wondering if I could manually enter commands in my CLI to test the code I've written.

**Comment by andrewtavis** [comment]
That can be done, yes! Here are the commands:

```bash
pip install --upgrade pip  # make sure that pip is at the latest version
pip install -r requirements.txt  # install dependencies
pip install -e .  # install the local version of Scribe-Data such that saved changes in the files will be reflected in CLI functionality

# Some extra helpful commands for working on Scribe-Data that are in the section of the docs that I got the above:
pre-commit install  # install pre-commit hooks that check your files for common errors before you commit
# pre-commit run --all-files  # lint and fix common problems in the codebase
```

Hope this helps! I'll go ahead and assign you here, but please let us know if there are further questions 😊

**Comment by harikrishnatp** [comment]
@andrewtavis, I've fixed the issue with the get functionality and am in the process of writing tests for it. I'll send the PR soon. Thank you for the guidance!

**Comment by andrewtavis** [comment]
Happy to help, @harikrishnatp! Really looking forward to the PR :)

**Comment by harikrishnatp** [comment]
@andrewtavis, Could you go through the PR and tell if you need any changes ? Also, I haven't added test files for query_test.py file ? Do you want me to add it as well ? I'm still learning how to write tests and thought I could go further with it after getting feedbacks from you

**Comment by andrewtavis** [comment]
Amazing to see this, @harikrishnatp :) I'll give some feedback in the PR 😊

**Comment by andrewtavis** [comment]
#533 closes this 😊 Thanks for the amazing issue and idea, @SethiShreya, and thank you for the work to fix this functionality, @harikrishnatp! 🚀
