### ISSUE TITLE
Add PyICU to requirements.txt

### ISSUE THREAD

**Issue by MdSayemkhan** [scribe-org/Scribe-Data#501]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Currently, running certain commands (e.g., scribe-data get -lang english -dt emoji_keywords) prompts the installation of PyICU if it’s not already installed, leading to an interruption in command execution. Adding PyICU to requirements.txt would ensure all dependencies are installed upfront, providing a smoother setup experience for users.

### Contribution

I'm happy to help test or review the change if needed. I could look into making this change in the requirements.txt file to add PyICU.

**Comment by andrewtavis** [comment]
Hey @MdSayemkhan 👋 I can understand how this would be confusing at first glance, but this behavior is intentional. PyICU requires a setup that can't simply be done via Pip or another Python package manager, and adding it to `requirements.txt` easily breaks the project for Windows users and the CLDR dependencies of PyICU are easier to get up and running on Linux and macOS. Because of this, we removed this package from the dependencies and are providing documentation in the CLI for how to set it up.

**Comment by andrewtavis** [comment]
You'd be welcome to expand the docs a bit about this, if you'd like to help make this more clear to years :)

**Comment by andrewtavis** [comment]
I'll close this though 😊
