### ISSUE TITLE
Improve links to GitHub in documentation

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#91]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

One thing that would be great for Scribe-Data's documentation would be if the pages were linked to the page where the code was on GitHub rather than the page to edit the docs. I've seen this done for various projects. A Stack Overflow question on this topic that points to helpful docs can be found [here](https://stackoverflow.com/questions/20059953/linking-back-to-a-source-code-file-in-sphinx).

### Contribution

Happy to support someone who has interest in working on this!

**Comment by mhmohona** [comment]
I want to work on this issue.

**Comment by mhmohona** [comment]
@andrewtavis will you please explain the requirement bit more? 
We already have the code linked in doc file [here](https://github.com/scribe-org/Scribe-Data/blob/main/docs/source/notes.rst), dont we?

**Comment by andrewtavis** [comment]
I can look for an example of this, @mhmohona. On some readthedocs documentation that I've seen the top right of the page isn't a link to the documentation that says `Edit on GitHub`, but rather a page to the code itself. So on the page for utils we'd see `View code on GitHub` or something like this, and then clicking it would go to `utils.py` on GitHub.

**Comment by mhmohona** [comment]
So in simple words, changing this text into `View code on GitHub`? 
![image](https://github.com/scribe-org/Scribe-Data/assets/14244685/6e239c34-215b-4d69-b8de-05f62a421b4a)
Thats it @andrewtavis? 😅

**Comment by andrewtavis** [comment]
Not quite, @mhmohona :) When you click that link you go to editing the file on GitHub that's for the docs. We want the link to go to the actual code file.

**Comment by mhmohona** [comment]
Thank you for patiently explaining me about the issue @andrewtavis. 🙏
I have understood the requirement now.

So I have tried various ways but failing to link customize link (python code file's link) instead of doc link. It would really help if you could give me a reference project as you mentioned in issue description.

However, if I put code link like afkmc2 put, will it meet the purpose? 
https://afkmc2.readthedocs.io/en/latest/reference.html

**Comment by codeIntrovert** [comment]
Looks like this issue is still not fixed, I will try fixing this and let you know how it goes.
From the conversation above what I believe the problem is when user clicks on `Edit On Github` right now user is redirected to the Docs stored on github, rather user should be redirected to the code file it self, for example `utils.py`
@andrewtavis

**Comment by andrewtavis** [comment]
Hi @codeIntrovert: this issue is already assigned to @mhmohona. Could I asked that you look for a different issue?

@mhmohona, having a link below the header would be enough to close this :) This is a great idea, thanks!
